# Generated by Django 2.2.3 on 2019-07-05 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=200, null=True)),
                ('is_image', models.BooleanField(default=False)),
                ('image_url', models.CharField(blank=True, max_length=200, null=True)),
                ('answer', models.CharField(max_length=200)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Collection')),
            ],
        ),
    ]
