# Generated by Django 2.2.3 on 2019-07-23 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCollections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribe_date', models.DateField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Collection')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_count', models.IntegerField()),
                ('last_rep_date', models.DateField()),
                ('next_rep_date', models.DateField()),
                ('my_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.MyCollections')),
                ('original_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Collection')),
            ],
        ),
    ]
