# Generated by Django 2.2.3 on 2019-07-23 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_mycollections_myquestions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mycollections',
            old_name='user_id',
            new_name='user',
        ),
    ]
