# Generated by Django 2.2.3 on 2019-07-23 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20190723_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myquestions',
            name='original_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Question'),
        ),
    ]
