# Generated by Django 2.2.3 on 2019-07-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20190724_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='myquestions',
            name='e_factor',
            field=models.FloatField(blank=True, default=2.5),
        ),
    ]
