# Generated by Django 2.2.3 on 2019-07-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_myquestions_e_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='myquestions',
            name='last_interval',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
