# Generated by Django 2.2.3 on 2019-07-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20190726_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='rating',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='collection',
            name='ratings_count',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
